package `fun`.adaptive.wireformat.signature

object KotlinSignatures {
    const val ANY = "*"
    const val UNIT = "0"
    const val BOOLEAN = "Z"
    const val INT = "I"
    const val BYTE = "B"
    const val SHORT = "S"
    const val LONG = "J"
    const val FLOAT = "F"
    const val DOUBLE = "D"
    const val CHAR = "C"
    const val STRING = "T"
    const val UUID = "U"
    const val BOOLEAN_ARRAY = "[Z"
    const val INT_ARRAY = "[I"
    const val BYTE_ARRAY = "[B"
    const val SHORT_ARRAY = "[S"
    const val LONG_ARRAY = "[J"
    const val FLOAT_ARRAY = "[F"
    const val DOUBLE_ARRAY = "[D"
    const val CHAR_ARRAY = "[C"
    const val UINT = "+I"
    const val UBYTE = "+B"
    const val USHORT = "+S"
    const val ULONG = "+J"
    const val UINT_ARRAY = "[+I"
    const val UBYTE_ARRAY = "[+B"
    const val USHORT_ARRAY = "[+S"
    const val ULONG_ARRAY = "[+J"
}

