@startuml
!pragma teoz true

box Disconnecting Peer
participant App as c.app
participant AutoBackend as c.backend
participant ServiceConnector as c.connector
participant AutoWorker as c.worker
endbox

box Other Peer
participant AppService as o.app.service
participant AutoBackend as o.backend
participant ServiceConnector as o.connector

participant "AutoService" as o.service
participant "AutoWorker" as o.worker
endbox

c.app -> c.backend : stop
activate c.backend

c.backend -> c.connector: disconnect
activate c.connector

c.connector --> o.service: removePeer
activate o.service

o.service -> o.worker : removePeer
activate o.worker

o.worker -> o.backend : removePeer
activate o.backend

o.backend -> o.connector : onDisconnect
activate o.connector

o.connector -> o.backend
deactivate o.connector

o.backend -> o.worker
deactivate o.backend

o.worker -> o.service
deactivate o.worker

o.service --> c.connector
deactivate o.service

c.connector -> c.backend
deactivate c.connector

c.backend -> c.app
deactivate c.backend

@enduml