/*
 * Copyright © 2020-2024, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

@file:Suppress("unused")

package deprecated.css

val margin_0 = AdaptiveCssStyle("margin_0")
val margin_1 = AdaptiveCssStyle("margin_1")
val margin_2 = AdaptiveCssStyle("margin_2")
val margin_4 = AdaptiveCssStyle("margin_4")
val margin_6 = AdaptiveCssStyle("margin_6")
val margin_8 = AdaptiveCssStyle("margin_8")
val margin_12 = AdaptiveCssStyle("margin_12")
val margin_16 = AdaptiveCssStyle("margin_16")
val margin_24 = AdaptiveCssStyle("margin_24")
val margin_32 = AdaptiveCssStyle("margin_32")

val margin_top_0 = AdaptiveCssStyle("margin_top_0")
val margin_top_1 = AdaptiveCssStyle("margin_top_1")
val margin_top_2 = AdaptiveCssStyle("margin_top_2")
val margin_top_4 = AdaptiveCssStyle("margin_top_4")
val margin_top_6 = AdaptiveCssStyle("margin_top_6")
val margin_top_8 = AdaptiveCssStyle("margin_top_8")
val margin_top_12 = AdaptiveCssStyle("margin_top_12")
val margin_top_16 = AdaptiveCssStyle("margin_top_16")
val margin_top_24 = AdaptiveCssStyle("margin_top_24")
val margin_top_32 = AdaptiveCssStyle("margin_top_32")

val margin_right_0 = AdaptiveCssStyle("margin_right_0")
val margin_right_1 = AdaptiveCssStyle("margin_right_1")
val margin_right_2 = AdaptiveCssStyle("margin_right_2")
val margin_right_4 = AdaptiveCssStyle("margin_right_4")
val margin_right_6 = AdaptiveCssStyle("margin_right_6")
val margin_right_8 = AdaptiveCssStyle("margin_right_8")
val margin_right_12 = AdaptiveCssStyle("margin_right_12")
val margin_right_16 = AdaptiveCssStyle("margin_right_16")
val margin_right_24 = AdaptiveCssStyle("margin_right_24")
val margin_right_32 = AdaptiveCssStyle("margin_right_32")

val margin_bottom_0 = AdaptiveCssStyle("margin_bottom_0")
val margin_bottom_1 = AdaptiveCssStyle("margin_bottom_1")
val margin_bottom_2 = AdaptiveCssStyle("margin_bottom_2")
val margin_bottom_4 = AdaptiveCssStyle("margin_bottom_4")
val margin_bottom_6 = AdaptiveCssStyle("margin_bottom_6")
val margin_bottom_8 = AdaptiveCssStyle("margin_bottom_8")
val margin_bottom_12 = AdaptiveCssStyle("margin_bottom_12")
val margin_bottom_16 = AdaptiveCssStyle("margin_bottom_16")
val margin_bottom_24 = AdaptiveCssStyle("margin_bottom_24")
val margin_bottom_32 = AdaptiveCssStyle("margin_bottom_32")

val margin_left_0 = AdaptiveCssStyle("margin_left_0")
val margin_left_1 = AdaptiveCssStyle("margin_left_1")
val margin_left_2 = AdaptiveCssStyle("margin_left_2")
val margin_left_4 = AdaptiveCssStyle("margin_left_4")
val margin_left_6 = AdaptiveCssStyle("margin_left_6")
val margin_left_8 = AdaptiveCssStyle("margin_left_8")
val margin_left_12 = AdaptiveCssStyle("margin_left_12")
val margin_left_16 = AdaptiveCssStyle("margin_left_16")
val margin_left_24 = AdaptiveCssStyle("margin_left_24")
val margin_left_32 = AdaptiveCssStyle("margin_left_32")