/*
 * Copyright © 2020-2024, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

@file:Suppress("unused")

package deprecated.css

val padding_0 = AdaptiveCssStyle("padding_0")
val padding_1 = AdaptiveCssStyle("padding_1")
val padding_2 = AdaptiveCssStyle("padding_2")
val padding_4 = AdaptiveCssStyle("padding_4")
val padding_6 = AdaptiveCssStyle("padding_6")
val padding_8 = AdaptiveCssStyle("padding_8")
val padding_12 = AdaptiveCssStyle("padding_12")
val padding_16 = AdaptiveCssStyle("padding_16")
val padding_24 = AdaptiveCssStyle("padding_24")
val padding_32 = AdaptiveCssStyle("padding_32")

val padding_top_0 = AdaptiveCssStyle("padding_top_0")
val padding_top_1 = AdaptiveCssStyle("padding_top_1")
val padding_top_2 = AdaptiveCssStyle("padding_top_2")
val padding_top_4 = AdaptiveCssStyle("padding_top_4")
val padding_top_6 = AdaptiveCssStyle("padding_top_6")
val padding_top_8 = AdaptiveCssStyle("padding_top_8")
val padding_top_12 = AdaptiveCssStyle("padding_top_12")
val padding_top_16 = AdaptiveCssStyle("padding_top_16")
val padding_top_24 = AdaptiveCssStyle("padding_top_24")
val padding_top_32 = AdaptiveCssStyle("padding_top_32")

val padding_right_0 = AdaptiveCssStyle("padding_right_0")
val padding_right_1 = AdaptiveCssStyle("padding_right_1")
val padding_right_2 = AdaptiveCssStyle("padding_right_2")
val padding_right_4 = AdaptiveCssStyle("padding_right_4")
val padding_right_6 = AdaptiveCssStyle("padding_right_6")
val padding_right_8 = AdaptiveCssStyle("padding_right_8")
val padding_right_12 = AdaptiveCssStyle("padding_right_12")
val padding_right_16 = AdaptiveCssStyle("padding_right_16")
val padding_right_24 = AdaptiveCssStyle("padding_right_24")
val padding_right_32 = AdaptiveCssStyle("padding_right_32")

val padding_bottom_0 = AdaptiveCssStyle("padding_bottom_0")
val padding_bottom_1 = AdaptiveCssStyle("padding_bottom_1")
val padding_bottom_2 = AdaptiveCssStyle("padding_bottom_2")
val padding_bottom_4 = AdaptiveCssStyle("padding_bottom_4")
val padding_bottom_6 = AdaptiveCssStyle("padding_bottom_6")
val padding_bottom_8 = AdaptiveCssStyle("padding_bottom_8")
val padding_bottom_12 = AdaptiveCssStyle("padding_bottom_12")
val padding_bottom_16 = AdaptiveCssStyle("padding_bottom_16")
val padding_bottom_24 = AdaptiveCssStyle("padding_bottom_24")
val padding_bottom_32 = AdaptiveCssStyle("padding_bottom_32")

val padding_left_0 = AdaptiveCssStyle("padding_left_0")
val padding_left_1 = AdaptiveCssStyle("padding_left_1")
val padding_left_2 = AdaptiveCssStyle("padding_left_2")
val padding_left_4 = AdaptiveCssStyle("padding_left_4")
val padding_left_6 = AdaptiveCssStyle("padding_left_6")
val padding_left_8 = AdaptiveCssStyle("padding_left_8")
val padding_left_12 = AdaptiveCssStyle("padding_left_12")
val padding_left_16 = AdaptiveCssStyle("padding_left_16")
val padding_left_24 = AdaptiveCssStyle("padding_left_24")
val padding_left_32 = AdaptiveCssStyle("padding_left_32")