/*
 * Copyright © 2020-2024, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

@file:Suppress("unused")

package deprecated.css

val width_0 = AdaptiveCssStyle("width_0")
val width_1_px = AdaptiveCssStyle("width_1_px")
val width_2_px = AdaptiveCssStyle("width_2_px")
val width_4_px = AdaptiveCssStyle("width_4_px")
val width_6_px = AdaptiveCssStyle("width_6_px")
val width_8_px = AdaptiveCssStyle("width_8_px")
val width_10_px = AdaptiveCssStyle("width_10_px")
val width_12_px = AdaptiveCssStyle("width_12_px")
val width_14_px = AdaptiveCssStyle("width_14_px")
val width_16_px = AdaptiveCssStyle("width_16_px")
val width_20_px = AdaptiveCssStyle("width_20_px")
val width_24_px = AdaptiveCssStyle("width_24_px")
val width_28_px = AdaptiveCssStyle("width_28_px")
val width_32_px = AdaptiveCssStyle("width_32_px")
val width_36_px = AdaptiveCssStyle("width_36_px")
val width_40_px = AdaptiveCssStyle("width_40_px")
val width_44_px = AdaptiveCssStyle("width_44_px")
val width_48_px = AdaptiveCssStyle("width_48_px")
val width_56_px = AdaptiveCssStyle("width_56_px")
val width_64_px = AdaptiveCssStyle("width_64_px")
val width_80_px = AdaptiveCssStyle("width_80_px")
val width_96_px = AdaptiveCssStyle("width_96_px")
val width_112_px = AdaptiveCssStyle("width_112_px")
val width_128_px = AdaptiveCssStyle("width_128_px")
val width_144_px = AdaptiveCssStyle("width_144_px")
val width_160_px = AdaptiveCssStyle("width_160_px")
val width_176_px = AdaptiveCssStyle("width_176_px")
val width_192_px = AdaptiveCssStyle("width_192_px")
val width_208_px = AdaptiveCssStyle("width_208_px")
val width_224_px = AdaptiveCssStyle("width_224_px")
val width_240_px = AdaptiveCssStyle("width_240_px")
val width_256_px = AdaptiveCssStyle("width_256_px")
val width_288_px = AdaptiveCssStyle("width_288_px")
val width_320_px = AdaptiveCssStyle("width_320_px")
val width_384_px = AdaptiveCssStyle("width_384_px")

val width_25_percent = AdaptiveCssStyle("width_25_percent")
val width_33_percent = AdaptiveCssStyle("width_33_percent")
val width_40_percent = AdaptiveCssStyle("width_40_percent")
val width_50_percent = AdaptiveCssStyle("width_50_percent")
val width_66_percent = AdaptiveCssStyle("width_66_percent")
val width_75_percent = AdaptiveCssStyle("width_75_percent")
val width_80_percent = AdaptiveCssStyle("width_80_percent")
val width_100_percent = AdaptiveCssStyle("width_100_percent")

val width_100_view_width = AdaptiveCssStyle("width_100_view_width")

val width_auto = AdaptiveCssStyle("width_auto")
val width_min_content = AdaptiveCssStyle("width_min_content")
val width_max_content = AdaptiveCssStyle("width_max_content")
val width_fit_content = AdaptiveCssStyle("width_fit_content")

