package `fun`.adaptive.auto.api

import `fun`.adaptive.adat.AdatClass

/**
 * @property  backendOnly  Then true, the listener will be called only for changes
 *                         generated by other backends. So, changes made by the local
 *                         frontend won't generate a listener call.
 */
abstract class AutoItemListener<A : AdatClass>(
    val backendOnly: Boolean = false,
) {

    open fun onChange(newValue: A, oldValue : A?) = Unit

}