package `fun`.adaptive.auto.api

import `fun`.adaptive.adat.AdatClass
import `fun`.adaptive.auto.model.ItemId

/**
 * @property  backendOnly  Then true, the listener will be called only for changes
 *                         generated by other backends. So, changes made by the local
 *                         frontend won't generate a listener call.
 */
abstract class AutoItemListener<IT : AdatClass>(
    val backendOnly: Boolean = false,
) {

    open fun onChange(itemId : ItemId, newValue: IT, oldValue : IT?) = Unit

    open fun onRemove() = Unit

}